# Generated by Django 5.2.7 on 2025-10-26 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Track',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название трека')),
                ('artist', models.CharField(max_length=100, verbose_name='Исполнитель')),
                ('anime', models.CharField(max_length=100, verbose_name='Аниме')),
                ('image', models.ImageField(blank=True, null=True, upload_to='track_images/', verbose_name='Обложка')),
                ('audio_file', models.FileField(upload_to='tracks/', verbose_name='Аудио файл')),
                ('duration', models.IntegerField(default=0, verbose_name='Длительность (секунды)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Трек',
                'verbose_name_plural': 'Треки',
            },
        ),
    ]
