# Generated by Django 5.2.7 on 2025-10-26 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='track',
            name='anime_rating',
            field=models.FloatField(default=0, verbose_name='Рейтинг аниме на MAL'),
        ),
        migrations.AddField(
            model_name='track',
            name='calculated_score',
            field=models.FloatField(default=0, verbose_name='Общий балл популярности'),
        ),
        migrations.AddField(
            model_name='track',
            name='spotify_popularity',
            field=models.IntegerField(default=0, verbose_name='Популярность в Spotify'),
        ),
    ]
