# Generated by Django 5.2.7 on 2025-11-02 03:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0002_track_anime_rating_track_calculated_score_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='track',
            options={},
        ),
    ]
