# Generated by Django 5.2.7 on 2025-11-30 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0005_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='track',
            name='lyrics',
            field=models.TextField(blank=True, null=True, verbose_name='Текст песни'),
        ),
    ]
