# Generated by Django 5.2.7 on 2025-12-01 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0006_track_lyrics'),
    ]

    operations = [
        migrations.AddField(
            model_name='track',
            name='lyrics_romanized',
            field=models.TextField(blank=True, null=True, verbose_name='Текст песни (ромадзи)'),
        ),
        migrations.AlterField(
            model_name='track',
            name='lyrics',
            field=models.TextField(blank=True, null=True, verbose_name='Текст песни (английский)'),
        ),
    ]
