# Generated by Django 5.2.7 on 2025-12-14 07:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0007_track_lyrics_romanized_alter_track_lyrics'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='is_deleted_account',
            field=models.BooleanField(default=False, verbose_name='Удаленный аккаунт'),
        ),
        migrations.AddField(
            model_name='comment',
            name='username_backup',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Имя пользователя (бэкап)'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
    ]
